@startuml Seq_Deposit
actor Customer
participant AccountView
participant AccountController
participant AccountDAO
participant Account

Customer -> AccountView: choose account + enter amount
AccountView -> AccountController: depositRequest(accountId, amount)
AccountController -> Account: deposit(amount)
Account -> AccountController: updateBalance
AccountController -> AccountDAO: saveTransaction(accountId, transaction)
AccountDAO -> AccountController: success
AccountController -> AccountView: displayUpdatedBalance()
@enduml
